@baseurl = http://localhost:8000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJZYWh5eWEgaGEiLCJpc3MiOiJtaW5pLXNlcnZpY2UiLCJpYXQiOjE2NjMzMzU2OTIuNDQxLCJleHAiOjE2NjMzMzkyOTIuNDQxfQ.czWHbN48VN-zDPLjyfWRmMz6VF-3S2OF3Du_7xzGorE

### Welcome
GET {{baseurl}} HTTP/1.1

### Register
POST {{baseurl}}/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Yahyya2",
    "tel_num": "9826471",
    "referal": ""
}

### Login
POST {{baseurl}}/auth/login HTTP/1.1
content-type: application/json

{
    "name": "Yahyya ha",
    "tel_num": "98264701",
    "referal": ""
}

### GET ALL PRODUCT
GET {{baseurl}}/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### GET PRODUCT BY ID
GET {{baseurl}}/products/search?id=1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### GET ALL CATEGORY
GET {{baseurl}}/categories HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### GET PRODUCT BY CATEGORY
GET {{baseurl}}/products/search?category=5 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### ADD A PRODUCT TO CART
POST {{baseurl}}/cart HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
{
    "user_id" : 1,
    "product_id" : 3,
    "quantity" : 2
}

### GET ALL CARTS
GET {{baseurl}}/cart HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### GET CART BY PRODUCT_ID
GET {{baseurl}}/cart/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### UPDATE CART BY PRODUCT_ID
PUT {{baseurl}}/cart HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
{
    "user_id" : 1,
    "product_id" : 3,
    "quantity" : 5
}

### DELETE CART BY PRODUCT_ID
DELETE {{baseurl}}/cart/3 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}